<center>
<img src="imagenes/logo-FCEN.png" alt="FCEN" style="width:1200px;"/>
</center>

<font size= "6">Curso de posgrado y materia optativa     
**Introducción a la programación en R en Biología** </font>

**Docentes:**

*   Dra. Melisa Olave
*   Dra. Laura García
*   Lic. Leonardo Gatica
*   Lic. María Virginia Chirilá
*   Belén Battistela

Material elaborado por María Virginia Chirilá

---
<font size= "6">**Clase 1 - Introducción a R**</font>

# 🚀Objetivos de esta clase
*   Entender que es R y que es RStudio.
*   Aprender que ventajas tiene R sobre Excel y otros lenguajes de programación
*   Familiarizarse con la interfaz de Rstudio.
*   Aprender a descargar R y Rstudio.
*   Conocer los diferentes tipos de datos (integrer, numeric, character, logical y complex).
*   Conocer los tipos de objetos básicos en R (vectores, matrices, listas, tablas, data frames).
*   Conocer los diferentes operadores lógicos y realizar operaciones con ellos.


# Índice
<p style="text-align: justify; line-height: 1.6; font-size:16px">

- [1 - ¿Qué es R?](#1)
- [2 - ¿Qué ventajas tiene R sobre Excel y otros lenguajes de programación?](#2)
- [3 - ¿Qué es RStudio?:](#3)
- [4 - ¿Cómo descargar R y RStudio](#4)
- [5 - Interfaz de RStudio](#5)
- [6 - Primeros pasos programando en R](#6)
    - [6.1 - Variables](#6.1)
    - [6.2 - Reglas para definir variables](#6.2)
- [7 - Tipos de datos en R](#7)
    - [7.1 - Datos numéricos (numeric)](#7.1)
    - [7.2 - Enteros (integer)](#7.2)
    - [7.3 - Complejos (complex)](#7.3)
    - [7.4 - Caracteres (character o string)](#7.4)
    - [7.5 - Lógicos (logic o boolean)](#7.5)
    - [7.6 - Factores (factor)](#7.6)
    - [7.7 - Datos especiales](#7.7)
    - [7.8 - Conversión de tipos de datos](#7.8)
- [8 - Tipos de estructuras de datos en R](#8)
    - [8.1 - Vectores](#8.1)
        - [8.1.1 - Conocer la estructura de un vector](#8.1.1)
        - [8.1.2 - Crear vectores ](#8.1.2)
        - [8.1.3 - Combinar vectores](#8.1.3)
        - [8.1.4 - Repetir vectores](#8.1.4)
        - [8.1.5 - Trabajar con indices](#8.1.5)
        - [8.1.6 - Trabajar con operadores](#8.1.6)
        - [8.1.7 - Operaciones matemáticas con vectores](#8.1.7)  
    - [8.2 - Matrices](#8.2)
    - [8.3 - Data frames](#8.3)
        - [8.3.1 - Crear data frames](#8.3.1)
        - [8.3.2 - Conocer la estructura de un data frames](#8.3.2)
        - [8.3.3 - Extraer datos de un data frame](#8.3.3)
        - [8.3.4 - Unir data frames por columnas](#8.3.4)
        - [8.3.5 - Agregar o modificar datos en un data frame](#8.3.5)
        - [8.3.6 - Utilizar operadores lógicos para filtrar datos](#8.3.6)
    - [8.4 - Listas](#8.4)
- [9 - Referencias](#9)
</p>

# **Antes de empezar**
Google Colab primeramente trabaja con Pyhton como entorno de ejecución. Por eso, para poder correr las celdas de código de este notebook tenemos que cambiar el entorno de ejecución en el menú que esta arriba a la derecha. Ver imagen.
<center>
<img src="imagenes/entorno1.png" alt="FCEN" style="width:400px;"/>
</center>


Seleccionar R como entorno de ejecución 

<center>
<img src="imagenes/entorno2.png" alt="entorno" style="width:400px;"/>
</center>


<a name='1'></a>
#  **1) ¿Qué es R?** 💻📈
R es un lenguaje de programación orientado a la manipulación y al análisis estadístico. Su diseño estuvo fuertemente influenciado por el lenguaje estadístico S, desarrollado por AT&T (una multinacional estadounidense), y es en gran medida compatible con él. El nombre S, de estadística, aludía a otro lenguaje de programación de una sola letra desarrollado en AT&T: el famoso lenguaje C.
Podemos decir que R tiene numerosas ventajas sobre otros software estadísticos, entre ellas:

* Es un lenguaje de programación **gratuito y open source**.
* Tiene gran **potencia** para todo tipo de **procesamiento y manipulación de datos**.
* Es utilizado por una amplia **comunidad** de programadores, académicos y profesionales.
* Permite la creación de todo tipo de **gráficos y visualizaciones** de datos con calidad de publicación.
* Tiene una gran colección de **paquetes complementarios** de distribución gratuita.
* Permite la **automatización** del trabajo.
* Es **multiplataforma**, esta disponible para los sistemas operativos Windows, Mac y Linux.
* Además de proporcionar operaciones estadísticas, R es un lenguaje de programación de **propósito general**, por lo que puede utilizarse para crear nuevas funciones que amplíen las características existentes del lenguaje.
* Incorpora características de **programación orientada a objetos y funcional**.
* El sistema guarda los conjuntos de datos entre sesiones, por lo que no es necesario recargarlos cada vez. También guarda el **historial de comandos**.
* Dado que R es un software de código abierto, es **fácil obtener ayuda** de la comunidad de usuarios.
* La generación de nuevas funciones o paquetes surgen del **aporte de los usuarios**, muchos de los cuales son destacados estadísticos.


<a name='2'></a>
# **2) ¿Qué ventajas tiene R sobre Excel y otros lenguajes de programación?** 💪📊  

## Ventajas de R sobre Excel
|        Excel	|     R            |
|---------------|------------------|
|Interfaz gráfica intuitiva |	Basado en código (más reproducible)|
|Difícil trabajar con grandes datasets|Escalable a grandes datasets|
|Limitado en análisis estadístico|	Librerías y funciones estadísticas avanzadas|
|Poco automatizable	|Fácil de automatizar y crear reportes dinámicos|

## Ventajas de R sobre otros lenguajes (Python, SPSS, etc.)
* R tiene una enorme cantidad de paquetes estadísticos.
* Paquetes específicos para análisis biológicos, ecología, bioestadística.
* La comunidad académica usa R, muchos papers en biología reproducen análisis en R.
* Aunque Python es mejor en análisis como machine learning, R es mejor en análisis estadístico.


<a name='3'></a>
#  **3) ¿Qué es RStudio?** 💻
RStudio es un entorno de desarrollo integrado (IDE, Integrated Drive Electronics) que hace más amigable trabajar con R. Facilita la escritura de código, la visualización de gráficos y el manejo de archivos.  Si bien podemos utilizar R desde la terminal de usuario, resulta mucho más fácil trabajar en la interfaz de RStudio que entre otras cosas tiene como ventajas que:
* Resalta partes de código, asignando diferentes colores a palabras clave y variables, lo que facilita la lectura
* Permite coincidencia automática de corchetes y paréntesis
* Tiene auto-completado de código: evita tener que escribir todos los comandos
* Permite carga de datos intuitiva.
* Permite fácil acceso a la Ayuda de R, con funciones útiles para explorar funciones y sus parámetros.
* Permite fácil exploración de variables y valores

<a name='4'></a>
#  **4) ¿Cómo descargar R y RStudio?** 💾
Para este curso vamos a utilizar R y RStudio. Se puede trabajar desde la consola en R, pero recomendamos utilizar RStudio como interfaz para que el proceso de aprendizaje sea mas amigable.
Entonces, si queres trabajar desde la consola de R sin utilizar RStudio, deberás descargar sólo R.
Si querés trabajar con R en RStudio tendrás que descargarte ambos.   

**⚠  Atención!** Para trabajar en RStudio, si o si necesitas tener R descargado en la computadora. Recordemos que RStudio es solo la interfaz, R es el que realiza los análisis, así que si o si necesitas ambos en tu computadora para poder trabajar.

<font size= "5" color= "black">**Descarga R**</font>

* **Descarga Windows:** https://cran.r-project.org/bin/windows/
* **Descarga Linux:** https://cran.r-project.org/bin/linux/
* **Descarga Mac:** https://cran.r-project.org/bin/macosx/

<font size= "5" color= "black">**Descarga RStudio**</font>

 https://posit.co/download/rstudio-desktop/ (Buscar la versión y el sistema operativo en la página)

<a name='5'></a>
#  **5) Interfaz de RStudio** 💻
Cuando abrimos RStudio podemos ver 4 ventanas además de la barra de opciones en la parte superior.
* **1. Escritor de código (scripts):** en esta ventana editamos y escribimos nuestro código. Sirve como un borrador ya que lo que se escribe aquí no se ejecuta (a no ser que se cliquee el botón **run** (correr)). En esta ventana podemos crear o editar nuestros scripts y luego guardarlos.

* **2. Consola:** Corresponde a lo que sería la consola de R (es lo que veríamos si trabajaramos en R sin RStudio). En esta parte se ejecuta el script contenido en el escritor de código (ventana uno). Aunque conviene trabajar sobre el escritor de código y luego ejecutar, es posible también trabajar directamente en la consola, en este caso todo lo que escribamos se ejecutará cuando demos Enter sin emabrgo, no quedará guardado en el script.

*  **3. Entorno:** en esta ventana podemos ver todos los objetos que estan en nuestro ambiente de trabajo. Los objetos que aparecen en el entorno solo corresponden a objetos que fueron guardados como variables. Las variables son elementos que permiten guardar datos e información. Las variables reciben un nombre (el que queramos) al que se le asigna un elemento específico que puede ser desde números hasta tablas o gráficos *(Ejemplo: En la imagen podemos ver que la variable X contenida en el entorno, continene un elemento de tipo character "Hola mundo" y que esa variable se creo en la primera línea de código del script al ejecutar X <- "Hola mundo")*.

* **4. Archivos, gráficos, ayuda, etc:** en esta ventana tenemos varias solapas de las cuales las más importantes son: (1) Files: permite ver los archivos dentro de nuestro directorio de trabajo, (2) Plots: proyecta los gráficos cuando se ejecutan en la consola, (3) Packages: permite instalar paquetes nuevos y actualizar y activar los paquetes ya instalados en nuestra computadora así como acceder a la información del número de versión y una descripción de estos, (4) Help: en esta solapa podemos acceder de manera sencilla a la información sobre determinados paquetes o funciones que nos interesen.



<center>
<img src="imagenes/interfaz-RStudio.jpg" alt="interfaz" style="width:600px;"/>
</center>



<a name='6'></a>
# **6) Primeros pasos programando en R** 🍼

<a name='6.1'></a>
## 6.1) Variables
Una variable en términos simples es un espacio de memoria que contiene información (números, caracteres, tablas, etc).

Podemos definir una variable en R utilizando esta combinación de caracteres **<-** o el signo igual **=**, así:

      mi_variable <- dato
      mi_variable2 = dato


In [6]:
# En R los # permiten dejar comentarios en el codigo sin que se ejecuten

# Por ejemplo, podemos definir una variable de nombre x que contenga el texto "Hola"
x <- "Hola"
print(x) # La función print permite imprimir en pantalla la variable.

[1] "Hola"


Asignar un valor a una variable significa que ese nombre hará referencia a un objeto específico, permitiendo acceder y manipular su contenido a través de él.
En nuestro ejemplo x contiene la palabra "Hola". Por ejemplo, si alguna vez necesito escribir "Hola" de nuevo simplemente puedo imprimir x, que se contiene esta palabra.


In [7]:
cat(x, "a todos") # cat es una función que se usa para imprimir texto y valores en la consola de manera más controlada que print

Hola a todos

Las variables pueden cambiar de valor. Por ejemplo

In [8]:
print(x) # Aquí x es = a "Hola"


[1] "Hola"


In [9]:
#Cambio el valor de x
x <- "Hola, como están"
cat(x, "todos?") #Aquí x cambio a "Hola, como están"

Hola, como están todos?

<font size= 4 color="firebrick"> **⚠ No todos los carácteres, palabras o valores son válidos como variables. Existen reglas para definirlas** </font>

<a name='6.2'></a>
## 6.2) Reglas para definir variables

* R diferencia entre mayúsculas y minúsculas. Es decir, por ejemplo las variables Variable_1 y variable_1 son **DOS variables DISTINTAS**.

In [10]:
# Por ejemplo
Variable <- 10  # Definimos una variable llamada "Variable" con mayúscula al principio

# Imprimimos variable (con minúscula en vez de mayúscula)
print(variable)  # Esto generará un error porque "variable" no existe en nuestro entorno de trabajo

ERROR: Error in eval(expr, envir, enclos): objeto 'variable' no encontrado


* Los nombre de las variables sólo pueden contener letras, dígitos, puntos y guión bajo (_). Pero no pueden tener guión alto (-)


In [11]:
dato_1 <- 1
print(dato_1)

dato.1 <- "UNCuyo"
print(dato.1)

dato-1 <- 235
print(dato-1) # Esto dará error

[1] 1
[1] "UNCuyo"


ERROR: Error: objeto 'dato' no encontrado


* Las variables siempre deben comenzar con una letra.

In [12]:
123variable <- 123
print(123variable) #Esto dará error

ERROR: Error in parse(text = x, srcfile = src): <text>:1:4: unexpected symbol
1: 123variable
       ^


* Existen palabras reservadas que no pueden utilizarse como nombres de variables o funciones, ya que tienen un significado especial dentro de R.

Estas palabras son: **if, else, repeat, while, function, for, in, next, break, TRUE, FALSE, NULL, Inf, NaN, NA, NA_integer_, NA_real_, NA_complex_ y NA_character_**



In [13]:
# Ejemplo
 NA <- "datos" #esto da error

ERROR: Error in NA <- "datos": lado izquierdo de la asignación inválida (do_set)


Para poder poder ver el listado completo podemos ejecutar "reserved" dentro de la función help()

In [14]:
help("reserved")

<a name='7'></a>
# **7) Tipos de datos en R** 🧱
R puede trabajar con diferentes tipos de datos los cuales te permiten realizar diferentes tipos de operaciones. Entre los tipos de datos con los que trabaja R se encuentran:

  * Númericos (numeric)
  * Enteros (integer)
  * Complejos (complex)
  * Caracteres (character o string)
  * Lógicos (logical o boolean)
  * Factores (factor)
  * Valores especiales (NA, Nan, Inf)

<a name='7.1'></a>
## 7.1) Datos numéricos (numeric)
Son números con o sin decimales. En R, los valores numéricos por defecto son de tipo double (punto flotante). Los tipos de datos double representan números en punto flotante de doble precisión (double-precision floating point). Los números double se almacenan usando 64 bits, lo que permite representar valores con alta precisión y un amplio rango de magnitudes (positivos y negativos, con decimales).


In [15]:
m <- 10        # Número entero (pero en realidad es "double" por defecto)
pi_ <- 3.14      # Número decimal
print(m)
print(pi_)

[1] 10
[1] 3.14


In [16]:
class(m) # la función class() permite acceder a información del tipo de dato

[1] "numeric"

In [17]:
class(pi_)

[1] "numeric"

<a name='7.2'></a>
## 7.2) Enteros (integer)
Son números enteros sin decimales.Se pueden definir usando L.

In [18]:
num1 <- 25      # Es "double o numeric" por defecto
num2 <- 25L     # Es "integer"

class(num1)  # "double o numeric"
class(num2)  # "integer"

[1] "numeric"

[1] "integer"

<a name='7.3'></a>
## 7.3) Complejos (complex)
Son números complejos es decir con una parte imaginaria, se representan con i

In [19]:
num_complejo <- 3 + 2i
print(num_complejo)
class(num_complejo)  # "complex"

[1] 3+2i


[1] "complex"

<a name='7.4'></a>
## 7.4) Caracteres (character o string)
Son cadenas de texto y pueden definirse entre comillas dobles o simples.

In [20]:
nombre <- "Ana"
mensaje <- 'Hola, mundo'
print(nombre)
print(mensaje)

class(nombre)
class(mensaje)

[1] "Ana"
[1] "Hola, mundo"


[1] "character"

[1] "character"

<a name='7.5'></a>
## 7.5) Lógicos (logic o boolean)
Tienen solo dos valores posibles: TRUE o FALSE.



In [21]:
es_mayor <- TRUE
print(es_mayor)
class(es_mayor)  # "logical"

[1] TRUE


[1] "logical"

<a name='7.6'></a>
## 7.6) Factores (factor)
Se usan para definir datos categóricos.



In [22]:
genero <- factor(c("Mujer", "Hombre", "Mujer", "Mujer", "Hombre"))
print(genero)
class(genero)

[1] Mujer  Hombre Mujer  Mujer  Hombre
Levels: Hombre Mujer


[1] "factor"

<a name='7.7'></a>
## 7.7) Datos especiales
R tiene valores especiales para manejar datos faltantes o indefinidos

| Valor | Significado                             |
|-------|-----------------------------------------|
| NA    | Dato faltante (Not Available)           |
|NaN	  |No es un número (Not a Number)           |
|Inf	  |Infinito positivo                        |
|-Inf	  |Infinito negativo                        |
|NULL	  |Representa la ausencia total de un valor |

In [23]:
j <- NA
s <- NaN
p <- Inf

print(is.na(j))   # TRUE (verifica si un valor es NA)
print(is.nan(s))  # TRUE (verifica si un valor es NaN)
print(1/0)        # Inf

[1] TRUE
[1] TRUE
[1] Inf


<a name='7.8'></a>
## 7.8) Conversión de tipos de datos
Podemos convertir entre tipos con funciones como as.numeric(), as.character(), as.logical(), etc.

In [24]:
num <- "100"         # Es un string porque esta entre comillas
class(num)
num_convertido <- as.numeric(num)
class(num_convertido)  # "double"

[1] "character"

[1] "numeric"

In [25]:
# Podemos convertir los ceros y unos a booleanos
cero <- 0
uno <- 1
print(cero)
print(uno)

[1] 0
[1] 1


In [26]:
cero <- as.logical(0)  # FALSE
uno <- as.logical(1)  # TRUE

print(cero)
print(uno)

[1] FALSE
[1] TRUE


<a name='8'></a>
# **8) Tipos de estructuras de datos en R** 🏢
En R existen varias estructuras de datos que se utilizan para almacenar y manipular información. Cada una tiene características específicas y se usa en distintos contextos. Entre estas estructuras podemos encontrar a:


*   Vectores
*   Matrices
*   Data Frames
*   Listas
*   Arrays



<a name='8.1'></a>
## 8.1) Vectores
Un vector es un conjunto unidimensional de valores, **todos del mismo tipo**. Es la unidad más pequeña con la que se puede trabajar en R. Un valor único también es técnicamente un vector: un vector con un solo elemento. En matemáticas, los vectores casi siempre se usan con valores numéricos, pero en R también pueden incluir otros tipos de datos, como cadenas de caracteres.

In [27]:
num_vec <- c(1, 2, 3, 4)      # Vector numérico
char_vec <- c("A", "B", "C")  # Vector de caracteres
log_vec <- c(TRUE, FALSE, TRUE)  # Vector lógico
dos <- 2 # Vector numérico

print(num_vec)  # [1] 1 2 3 4

[1] 1 2 3 4


<a name='8.1.1'></a>
### 8.1.1) Conocer la estructura de un vector

La función str() nos permite conocer la estructura de un vector. length() nos permite conocer el número de elementos de un vector

In [28]:
str(num_vec)

 num [1:4] 1 2 3 4


In [29]:
length(num_vec)

[1] 4

Podemos testear el tipo de vector con las funciones is.numeric(), is.integer(), is.character(), etc.

In [30]:
is.numeric(num_vec)

[1] TRUE

In [31]:
is.integer(num_vec)

[1] FALSE

<a name='8.1.2'></a>
### 8.1.2) Crear vectores

Podemos crear vectores de diferente manera:

*   Si nuestro vector tiene un solo elemento, simplemente asignamos el dato a una variable.
                numero <- 3
                nombre <- "julia"
*   Con la función concatenar c(). El nombre c() viene de "combine" (combinar) y permite reunir varios elementos del mismo tipo de datos en una sola estructura.
                comb <- c(1,5,7,9,123)
                comb_palabras <- c("Juan","Ana","Pablo")
*   Podemos utilizar c() y los : para crear vectores con secuencias de números en intervalos de uno.
                secuencia <- c(3:15)
Crea un vector con numeros del 3 al 15.
                secuencia_negativa <- -c(2:19)
Crea un vector con numeros del -19 al -2   
*   Crear una secuencia de valores numéricos con seq().
                sec_desc <- seq(from = 4.5, to = 2.5, by = -0.5)
En este caso crea una secuencia descendiente de 4.5 a 2.5 en intervalos de 0.5.
                sec_asc <- seq(from = 2.5, to = 4.5, by = 0.5)
Crea una secuencia ascendente de 2.5 a 4.5 en intervalos de 0.5.



<a name='8.1.3'></a>
### 8.1.3) Combinar vectores
Los vectores del mismo tipo se pueden combinar sin que el tipo de dato se modifique.



In [32]:
set1 <- c(12, 4, 4, 6, 9, 3)
set2 <- c(5, 3, 2, 2, 12, 9)
total <- c(set1 , set2)
print(total)

 [1] 12  4  4  6  9  3  5  3  2  2 12  9


Los vectores contienen datos del mismo tipo. Pero cuando uso c() para combinar datos de distinto tipo automáticamente R convierte todos los datos a character.

In [33]:
numero <- c(23,89,45)
palabras <- c("mesa", "silla")
logicos <- c(TRUE, FALSE, TRUE)

str(numero)
str(palabras)
str(logicos)

 num [1:3] 23 89 45
 chr [1:2] "mesa" "silla"
 logi [1:3] TRUE FALSE TRUE


In [34]:
combinacion <- c(numero,palabras, logicos)
str(combinacion)

 chr [1:8] "23" "89" "45" "mesa" "silla" "TRUE" "FALSE" "TRUE"


<a name='8.1.4'></a>
### 8.1.4) Repetir vectores
Se puede repetir un vector un número determinado de veces con la función rep()


In [35]:
rep(c(0, 0, 7), times = 3) #Repite el vector c(0,0,7) tres veces

[1] 0 0 7 0 0 7 0 0 7

In [36]:
rep("Hola", times=3)

[1] "Hola" "Hola" "Hola"

In [37]:
rep(c(2, 4, 2), each = 3) #Repite cada elemento del vector c(2,4,2) 3 veces

[1] 2 2 2 4 4 4 2 2 2

In [38]:
rep(c(0, 7), times = c(4, 2)) #Repite el primer elemento 4 veces y el segundo dos veces

[1] 0 0 0 0 7 7

In [39]:
rep(1:3, length.out = 7) # Repite el vector hasta alcanzar un maximo de 7 elementos

[1] 1 2 3 1 2 3 1

<a name='8.1.5'></a>
### 8.1.5) Trabajar con indices
En R se puede acceder a los elementos contenidos en un vector utilizando sus índices.
Cada elemento de un vector de R tiene asociado indice o index que es un valor numérico mayor igual a uno.

En R, para acceder a un elemento de un vector utilizo los corchetes [  ] y el número de índice del elemento/os que quiero obtener.

*Nota: en otros lenguajes de programación como Python el indice inicia en cero, es decir el primer elemento de un vector tiene indice = 0.*

Por ejemplo: si tengo un vector con una secuencia de numeros del 23 al 40 se que el número 25 tiene índice 3.



In [40]:
secuencia <- c(23:40)
print(secuencia)

 [1] 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40


In [41]:
secuencia[3] #Obtener el elemento 3 del vector secuencia

[1] 25

In [42]:
secuencia[1:3] #Puedo obtener más de un elemento

[1] 23 24 25

In [43]:
elementos_a_extraer <- c(1,18, 3:6)
secuencia[elementos_a_extraer] #puedo ontenerlos tambien en conjunto sin importar el orden en el vector

[1] 23 40 25 26 27 28

**Exclusión de elementos en un vector usando índices negativos**

En R, puedes usar un índice negativo (-) para excluir temporalmente un elemento de un vector. Por ejemplo, si quiero ver todos los elementos del vector secuencia excepto el número 25 (que está en la posición 3), ejecuto:

In [44]:

secuencia[-3]


[1] 23 24 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40

**Importante:** Esto no elimina el 25 del vector original, solo muestra una versión sin ese elemento.

In [45]:
# Podes excluir varios elementos de esta manera
secuencia[-c(1:3)]

[1] 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40

**Eliminación permanente de un elemento**

Si deseas eliminar definitivamente el 25 del vector secuencia, debes reasignar el resultado al mismo vector:

In [46]:
secuencia <- secuencia[-3]  # Sobreescribe el vector original
print(secuencia)

 [1] 23 24 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40


**Modificar valores existentes en un vector**

Puedes cambiar un elemento específico asignando un nuevo valor a su posición (índice).
Usa
            
             vector[índice] <- nuevo_valor
para reemplazar un elemento

In [47]:
# Vector original
frutas <- c("manzana", "banana", "naranja")
print(frutas)  # ["manzana", "banana", "naranja"]

# Cambiar "banana" (posición 2) por "pera"
frutas[2] <- "pera"
print(frutas)  # ["manzana", "pera", "naranja"]

[1] "manzana" "banana"  "naranja"
[1] "manzana" "pera"    "naranja"


**Agregar nuevos valores a un vector**

Para añadir elementos, usa índices más allá de la longitud actual del vector o funciones como c() (concatenar).

In [48]:
# Utilizando indices

print(frutas)

# Agregar uva en la posición 4 (que no existe aún)
frutas[4] <- "uva"
print(frutas)

[1] "manzana" "pera"    "naranja"
[1] "manzana" "pera"    "naranja" "uva"    


In [49]:
# utilizando c()
frutas2 <- c("mango","cereza","kiwi")
frutas <- c(frutas, frutas2)
print(frutas)

[1] "manzana" "pera"    "naranja" "uva"     "mango"   "cereza"  "kiwi"   


In [50]:
#Si asignas un nuevo elemento con numero de indice muy lejando, R rellenara los
# espacios con valores NA

frutas2[7] <- "mandarina"
print(frutas2)

[1] "mango"     "cereza"    "kiwi"      NA          NA          NA         
[7] "mandarina"


<a name='8.1.6'></a>
### 8.1.6) Trabajar con operadores


Los operadores lógicos en R se usan para evaluar condiciones y combinar expresiones que devuelven valores TRUE (verdadero) o FALSE (falso). Son esenciales en filtrado de datos, condicionales (if-else), y operaciones lógicas.

**Operadores lógicos en R**

|Operador|	Descripción|	Ejemplo|	Resultado (ejemplo)|
|--------|-------------|---------|---------------------|
|  ==    |	Igualdad	 | 5 == 5  |	TRUE |
|!=    	 | Desigualdad	|3 != 2|	TRUE|
|<       |	Menor que|	10 < 5	|FALSE|
|>       |	Mayor que        |	10 > 5|	TRUE|
|<=      |	Menor o igual que|	5 <= 5	|TRUE|
|>=	     |Mayor o igual que  |	8 >= 10|	FALSE|
|&	     | AND (y lógico) |	(5 > 3) & (2 < 4)	|TRUE (ambos verdaderos)|
| \|     |	OR (o lógico)|	(5 > 3) \| (1 > 2)|	TRUE (al menos uno verdadero)|
|!	     | NOT (negación lógica)|	!(5 == 5)|	FALSE|
|%in%	|Pertenece a un conjunto	|3 %in% c(1, 3, 5)	|TRUE|

**Operadores de comparación**

In [51]:
x <- 10
x > 8   # TRUE
x == 10 # TRUE
x != 5  # TRUE

[1] TRUE

[1] TRUE

[1] TRUE

**Operadores lógicos compuestos**

In [52]:
# Operador & (AND): Para que sea TRUE ambas condiciones deben ser verdaderas:
(x > 5) & (x < 15)

[1] TRUE

In [53]:
# Operador | (OR) al menor una condición debe ser verdadera para que sea TRUE
(x < 5) | (x == 10) # TRUE (aunque x < 5 es falso, x == 10 es verdadero)

[1] TRUE

In [54]:
# Operador ! (NOT): Invierte el resultado lógico:
!(x == 10)  # FALSE (porque x SÍ es igual a 10)

[1] FALSE

**Operadores especiales**

In [55]:
# Operador %in% Verifica si un valor está dentro de un conjunto
colores <- c("rojo", "azul", "verde")
"azul" %in% colores  # TRUE
"amarillo" %in% colores  # FALSE

[1] TRUE

[1] FALSE

In [56]:
#Ejemplo práctico
edades <- c(15, 22, 30, 17, 25)

# Filtro: edades mayores a 20 Y menores a 28
edades[edades > 20 & edades < 28]  # Devuelve: 22, 25

# Negación: edades que NO son 17
edades[edades != 17]  # Devuelve: 15, 22, 30, 25

[1] 22 25

[1] 15 22 30 25

<a name='8.1.7'></a>
### 8.1.7) Operaciones matemáticas con vectores
#### **Operaciones matemáticas básicas**

R tiene una serie de operadores aritmeticos para realizar calculos matemáticos.

**Operadores aritméticos**

|Operador|	Descripción   |	Ejemplo  |Resultado (x = 5, y = 2)|
|--------|----------------|----------|----------------------|
|   +    |	   Suma	      |x + y     |              	7     |
|\-      |	Resta         |	x - y   |	3                     |
|\*	     | Multiplicación |	x * y	|10                       |
|/       |	División      |	x / y	|2.5                      |
|^ o **  |	Potencia      |	x^y	  |25 (5 elevado a 2)|
|%%	     |Módulo (resto división)|x %% y|1 (5 ÷ 2 = 2 con resto 1)|
|%/%     |	División entera	|x %/% y|	2 (5 ÷ 2 = 2.5 → parte entera)|

**Utilizar operadores aritméticos con vectores**
Además de las operaciones básicas entre vectores de un elemento podemos realizar operaciones entre vectores más grandes. Ejemplo:

In [57]:
# Realicé un muestreo de nidos de abejas solitarias en dos sitios,
# cada uno con 6 puntos de muestreo. Recolecte esto
nidos_sitio1 <- c(12, 4, 4, 6, 9, 3)
nidos_sitio2 <- c(5, 3, 2, 2, 12, 9)

#Si se que el promedio de huevos por nido es de 5 podría estimar el total de
#huevos para cada punto de cada sitio así:
mediahuevos <- 5
huevos_sitio1 <- nidos_sitio1*mediahuevos
huevos_sitio2 <- nidos_sitio2*mediahuevos

print(huevos_sitio1)
print(huevos_sitio2)

[1] 60 20 20 30 45 15
[1] 25 15 10 10 60 45


In [58]:
#Si quisiera sumar todos los huevos por punto de muestreo podría

 huevos_totales <- huevos_sitio1 + huevos_sitio2
 print(huevos_totales)

[1]  85  35  30  40 105  60


**Funciones matemáticas útiles**

| Función | ¿Qué hace?|
|---------|-----------|
|abs(x) |Devuelve el valor absoluto de x|
|log(x, base = y) | Devuelve el logaritmo de x con base y; si no se especifica la base, devuelve el logaritmo natural|
|exp(x) |Devuelve el exponencial de x|
|sqrt(x) |Devuelve la raíz cuadrada de x|
|factorial(x)| Devuelve el factorial de x (¡x!)
|choose(x, y) |Devuelve el número de combinaciones posibles al extraer y elementos de x posibilidades|
|round(x, digits= y) | Redondea un número x con y decimales |
|floor(x) | Redondea al entero más cercano menor que x. Por lo tanto, floor(123.45) se convierte en 123 y floor(‐123.45) se convierte en –124||
|ceiling(x) |Redondea al entero más cercano mayor que x. Esto significa que ceiling(123.45) se convierte en 124 y ceiling(‐123.45) se convierte en –123|
|trunc(x)| Redondea al entero más cercano en la dirección de 0. Por lo tanto, trunc(123.65) se convierte en 123 y trunc(‐123.65) se convierte en –123|
|sum(x) | Suma todos los valores contenidos en x |


**Funciones estadísticas básicas en R**

**1. Medidas de Tendencia Central**

|Función|	Descripción|	Ejemplo (x <- c(2, 5, 7, 10, 15))|
|-------|------------|-----------------------------------|
|mean()|	Media aritmética|	mean(x) → 7.8|
|median()|	Mediana	|median(x) → 7|


**2. Medidas de Dispersión**

|Función|	Descripción|	Ejemplo (x <- c(2, 5, 7, 10, 15))|
|-------|-----------|----------------------------------|
|sd()	|Desviación estándar|	sd(x) → 4.924|
|var()	|Varianza	|var(x) → 24.2|
|range()|	Rango (mín y máx)|	range(x) → c(2, 15)|
|min() | Valor mínimo | min(x) → 2|
|max()| Valor máximo | max(x) → 15|
|IQR()|	Rango intercuartílico	|IQR(x) → 5 (Q3 - Q1)|
|quantile()|	Cuartiles/percentiles	|quantile(x, probs = 0.75) → 10 (Q3)|


<a name='8.2'></a>
## 8.2) Matrices

 Las matrices son estructuras bidimensionales donde todos los elementos son del mismo tipo (numérico, carácter, lógico, etc.).

 Podemos crear una matriz con la función matrix(). Sin embargo, es necesario proporcionar a R un poco más de información. R necesita saber qué valores se quieren incluir en la matriz y cómo. La función matrix() tiene varios argumentos para esto:
 * data: es un vector de valores que se desea incluir en la matriz.
 * ncol: toma un solo número que indica a R cuántas columnas se desean.
 * nrow: toma un solo número que indica a R cuántas filas se desean.
 * byrow: toma un valor lógico que indica a R si se desea completar la matriz por filas (VERDADERO) o por columnas (FALSO). Por columnas es el valor predeterminado.

In [59]:
vec <- c(1:20)
primer_matriz <- matrix(data = vec, ncol = 4)
print(primer_matriz)

     [,1] [,2] [,3] [,4]
[1,]    1    6   11   16
[2,]    2    7   12   17
[3,]    3    8   13   18
[4,]    4    9   14   19
[5,]    5   10   15   20


In [60]:
primer_matriz2 <- matrix(data = vec, ncol = 4, byrow = TRUE)
print(primer_matriz2)

     [,1] [,2] [,3] [,4]
[1,]    1    2    3    4
[2,]    5    6    7    8
[3,]    9   10   11   12
[4,]   13   14   15   16
[5,]   17   18   19   20


Podemos acceder a los valores de una matriz utilizando indices:
                    
                    matriz[fila, columna]

In [61]:
#Accedo al valor en la fila 2 de la columna 4
primer_matriz[2,4]

[1] 17

In [62]:
#Accedo a todos los valores en la fila 2
primer_matriz[2,]

[1]  2  7 12 17

In [63]:
#Accedo a todos los valores en la columna 4
primer_matriz[,4]

[1] 16 17 18 19 20

In [64]:
#Accedo a los valores de las filas 2 y 3 de la columna 4
primer_matriz[2:3,4]

[1] 17 18

In [65]:
#Accedo a los valores de las filas 2 y 5 de la columna 4
primer_matriz[c(2,5),4]

[1] 17 20

Podemos utilizar dos vectores de igual largo para crear una matriz con la función rbind() o cbind()


In [66]:
muestreo_nidos <- rbind(nidos_sitio1,nidos_sitio2)
muestreo_nidos

[,1] [,2] [,3] [,4] [,5] [,6]
nidos_sitio1 12   4    4    6     9   3   
nidos_sitio2  5   3    2    2    12   9

In [67]:
muestreo_huevos <- cbind(huevos_sitio1,huevos_sitio2)
muestreo_huevos

huevos_sitio1 huevos_sitio2
[1,] 60            25           
[2,] 20            15           
[3,] 20            10           
[4,] 30            10           
[5,] 45            60           
[6,] 15            45

<a name='8.3'></a>
## 8.3) Data Frames

Los data frames son estructuras bidimensionales similares a las matrices, pero con columnas con diferentes tipos de datos(numérico, carácter, etc.).



<a name='8.3.1'></a>
### 8.3.1) Crear data frames

**Podemos crear data frames a partir de matrices, tablas y vectores**

In [68]:
# A partir de vectores
puntos_muestreo <- c("P1","P2", "P3","P4","P5","P6")
observador <- c("Juan", "Juan", "Julia", "Martín","Martín","Juan y Julia")
df_ptos <- data.frame(puntos_muestreo, observador)
print(df_ptos)



  puntos_muestreo   observador
1              P1         Juan
2              P2         Juan
3              P3        Julia
4              P4       Martín
5              P5       Martín
6              P6 Juan y Julia


In [69]:
# A partir de una matriz
df_huevos <- as.data.frame( muestreo_huevos)
print(df_huevos)

  huevos_sitio1 huevos_sitio2
1            60            25
2            20            15
3            20            10
4            30            10
5            45            60
6            15            45


In [70]:
#Podemos utilizar los datos de las filas de una matriz y crear un data frame
print(muestreo_nidos)#La matriz

             [,1] [,2] [,3] [,4] [,5] [,6]
nidos_sitio1   12    4    4    6    9    3
nidos_sitio2    5    3    2    2   12    9


In [71]:
#usar las filas de la matriz para crear el data frame
df_nidos <- data.frame(nidos_sitio1 = muestreo_nidos[1,], nidos_sitio2= muestreo_nidos[2,])
print(df_nidos)

  nidos_sitio1 nidos_sitio2
1           12            5
2            4            3
3            4            2
4            6            2
5            9           12
6            3            9


In [72]:
# Crear un df a Partir de una tabla
conteo <- c("P1","P2","P1", "P2", "P3", "P4" ,"P6" ,"P1", "P4", "P2", "P3","P4","P5","P6")
num_especies <- table(puntos_muestreo= conteo)
print(num_especies)
# Las tablas son estruturas de datos que cuentan frecuencias
# de factores o variables categóricas

puntos_muestreo
P1 P2 P3 P4 P5 P6 
 3  3  2  3  1  2 


In [73]:
# Converir tabla en data frame
df_num_especies<- as.data.frame(num_especies)
print(df_num_especies)

  puntos_muestreo Freq
1              P1    3
2              P2    3
3              P3    2
4              P4    3
5              P5    1
6              P6    2


<a name='8.3.2'></a>
### 8.3.2) Conocer la estructura de un data frame

Existen funciones como summary(), str(), ncol(), nrow() y length() que nos permiten investigar sobre la estructura de nuestro data frame

In [74]:
str(df_huevos) #con str vemos cuantas observaciones tiene cada columna y cuantas variables hay

'data.frame':	6 obs. of  2 variables:
 $ huevos_sitio1: num  60 20 20 30 45 15
 $ huevos_sitio2: num  25 15 10 10 60 45


In [75]:
summary(df_huevos) # Con summary() podemos obtener algunas medidas estadísticas importantes

 huevos_sitio1   huevos_sitio2  
 Min.   :15.00   Min.   :10.00  
 1st Qu.:20.00   1st Qu.:11.25  
 Median :25.00   Median :20.00  
 Mean   :31.67   Mean   :27.50  
 3rd Qu.:41.25   3rd Qu.:40.00  
 Max.   :60.00   Max.   :60.00  

In [76]:
nrow(df_huevos) #podemos ver cuantas filas tiene el df

[1] 6

In [77]:
ncol(df_huevos) #Podemos ver cuantas columnas tiene el df

[1] 2

In [78]:
length(df_huevos) #Tambien nos dice cuantas columnas hay

[1] 2

In [79]:
names(df_huevos)#me permite ver los nombres de las variables colnames() también funciona

[1] "huevos_sitio1" "huevos_sitio2"

In [80]:
# head() nos permite ver las primeras filas del df
head(df_huevos, 3) #en el segundo argumento escirbimos la cantidad de filas que queremos ver

huevos_sitio1 huevos_sitio2
1 60            25           
2 20            15           
3 20            10

<a name='8.3.3'></a>
### 8.3.3) Extraer datos de un data frame

Al igual que las matrices los data frames tienen dos dimensiones por lo que podemos extraer valores de ellos utilizando indices:

                  data_frame[fila, columna]

Pero tambien podemos acceder con el nombre de la columna o con $

In [81]:
#accedemos al valor de la fila 1 de la columna 2
df_ptos[1,2]

[1] "Juan"

In [82]:
#Podemos obtener el mismo resultado si hacemos esto:
df_ptos[ 1, "observador"]

[1] "Juan"

In [83]:
# o si hacemos esto:
df_ptos$observador[1] #Seleccionamos el elemento uno de la columna observador

[1] "Juan"

In [84]:
# el simbolo $ nos permite acceder a los datos de columnas individuales
df_ptos$observador

[1] "Juan"         "Juan"         "Julia"        "Martín"       "Martín"      
[6] "Juan y Julia"

<a name='8.3.4'></a>
### 8.3.4) Unir data frames por columnas

Podemos unir dos o más data frames utilizando las funciones cbind() y merge(). Para evitar errores siempre debemos asegurarnos que el numero de filas es igual en los data frames que vamos a unir.

**cbind()** Te permite unir más de dos data frames sin tener en cuenta si las columnas se repiten o no entre df.

In [85]:
cbind(df_ptos,df_huevos,df_nidos, df_num_especies)

puntos_muestreo observador   huevos_sitio1 huevos_sitio2 nidos_sitio1
1 P1              Juan         60            25            12          
2 P2              Juan         20            15             4          
3 P3              Julia        20            10             4          
4 P4              Martín       30            10             6          
5 P5              Martín       45            60             9          
6 P6              Juan y Julia 15            45             3          
  nidos_sitio2 puntos_muestreo Freq
1  5           P1              3   
2  3           P2              3   
3  2           P3              2   
4  2           P4              3   
5 12           P5              1   
6  9           P6              2

Como vemos tenemos dos columnas con el mismo nombre y el mismo dato (puntos_muestreo). Para evitar columnas repetidas utilizamos merge que tiene en cuenta las columnas comunes y no las duplica.
Merge tiene distintos argumentos que nos permiten unir de forma diferente los data frames:

**Opciones de merge():**
 * by = "columna": Especifica la columna clave (la repetida).
 * all.x = TRUE: Left join (mantiene todas las filas del primer df).
 * all.y = TRUE: Right join (mantiene todas las filas del segundo df).
 * all = TRUE: Full join (mantiene todas las filas de ambos, incluyendo las repetidas).

El unico problema con merge es que solo permite unir de a dos data frames. Para obtener nuestro data frame final sin columnas repetidas nuestro código sería:

In [86]:

df_merged <- cbind(df_ptos,df_huevos,df_nidos) #Crear un df uniendo todos los df que no tengan iguales columnas
df_final <- merge(df_merged, df_num_especies, by = "puntos_muestreo") #Unir el df creado con el que tiene la columna en comun
df_final

puntos_muestreo observador   huevos_sitio1 huevos_sitio2 nidos_sitio1
1 P1              Juan         60            25            12          
2 P2              Juan         20            15             4          
3 P3              Julia        20            10             4          
4 P4              Martín       30            10             6          
5 P5              Martín       45            60             9          
6 P6              Juan y Julia 15            45             3          
  nidos_sitio2 Freq
1  5           3   
2  3           3   
3  2           2   
4  2           3   
5 12           1   
6  9           2

<a name='8.3.5'></a>
### 8.3.5) Agregar o modificar datos en un data frame **texto en negrita**

Podemos agregar datos a un data frame utilizando rbind() y modificar un dato específico o columna especifica utilizando los indices o $.

In [87]:
#por ejemplo tenemos un nuevo data frame con datos para agregar a nuestro data frame final

nuevos_datos <- data.frame(puntos_muestreo=c( "P1","P2", "P3","P4","P5","P6"),
                          observador= c("Ana", "Juan", "Ana y Juan", "Carlos", "Carlos", "Carlos") ,
                          huevos_sitio1= c(23,10,34,12,10,7),
                          huevos_sitio2= c(25, 17, 10, 12, 14,9),
                          nidos_sitio1= c(4,2,6,3,2,1),
                          nidos_sitio2= c(5,3,2,2,3,2),
                          Freq=c(2,2,1,1,4,5))
print(nuevos_datos)

  puntos_muestreo observador huevos_sitio1 huevos_sitio2 nidos_sitio1
1              P1        Ana            23            25            4
2              P2       Juan            10            17            2
3              P3 Ana y Juan            34            10            6
4              P4     Carlos            12            12            3
5              P5     Carlos            10            14            2
6              P6     Carlos             7             9            1
  nidos_sitio2 Freq
1            5    2
2            3    2
3            2    1
4            2    1
5            3    4
6            2    5


In [88]:
#Para agregar estos datos al df_final usamos rbind() la condicion es que los df
# tienen que tener igual numero de columnas y los nombres y el orden tienen que ser iguales

df_final <- rbind(df_final, nuevos_datos)
print(df_final)

   puntos_muestreo   observador huevos_sitio1 huevos_sitio2 nidos_sitio1
1               P1         Juan            60            25           12
2               P2         Juan            20            15            4
3               P3        Julia            20            10            4
4               P4       Martín            30            10            6
5               P5       Martín            45            60            9
6               P6 Juan y Julia            15            45            3
7               P1          Ana            23            25            4
8               P2         Juan            10            17            2
9               P3   Ana y Juan            34            10            6
10              P4       Carlos            12            12            3
11              P5       Carlos            10            14            2
12              P6       Carlos             7             9            1
   nidos_sitio2 Freq
1             5    3
2        

**Modificar un dato o registro particular**

In [89]:

#Por ejemplo queremos modificar en la columna observador el dato en la fila 6
# Juan y Julia por Juan
df_final[6 , "observador"] <- "Juan"

print(df_final[5:7, ],) # Vemos que el dato 6 en la columna observador cambio

  puntos_muestreo observador huevos_sitio1 huevos_sitio2 nidos_sitio1
5              P5     Martín            45            60            9
6              P6       Juan            15            45            3
7              P1        Ana            23            25            4
  nidos_sitio2 Freq
5           12    1
6            9    2
7            5    2


**Agregar columnas** Se puede agregar columnas nuevas con indices o con $ y dandole un nombre nuevo a nuestra variable.

In [90]:
# Quiero agregar datos sobre los años de muestreo
anios <- c(rep(2022, 6), rep(2023,6))
print(anios)

 [1] 2022 2022 2022 2022 2022 2022 2023 2023 2023 2023 2023 2023


In [91]:
#Puedo agregar esta nueva columna de esta manera
df_final$anios_muestreo <- anios
print(head(df_final))

  puntos_muestreo observador huevos_sitio1 huevos_sitio2 nidos_sitio1
1              P1       Juan            60            25           12
2              P2       Juan            20            15            4
3              P3      Julia            20            10            4
4              P4     Martín            30            10            6
5              P5     Martín            45            60            9
6              P6       Juan            15            45            3
  nidos_sitio2 Freq anios_muestreo
1            5    3           2022
2            3    3           2022
3            2    2           2022
4            2    3           2022
5           12    1           2022
6            9    2           2022


In [92]:
# o de esta manera
temperatura <- c(rep(25.5, 6), rep(30.7, 6))
df_final["temp_media"] <- temperatura
print(head(df_final))

  puntos_muestreo observador huevos_sitio1 huevos_sitio2 nidos_sitio1
1              P1       Juan            60            25           12
2              P2       Juan            20            15            4
3              P3      Julia            20            10            4
4              P4     Martín            30            10            6
5              P5     Martín            45            60            9
6              P6       Juan            15            45            3
  nidos_sitio2 Freq anios_muestreo temp_media
1            5    3           2022       25.5
2            3    3           2022       25.5
3            2    2           2022       25.5
4            2    3           2022       25.5
5           12    1           2022       25.5
6            9    2           2022       25.5


<a name='8.3.6'></a>
### 8.3.6) Utilizar operadores lógicos para filtrar datos en data frames

Se pueden utilizar operadores logicos para filtrar datos en nuestros data frames


In [93]:
# puntos de muestreo del sitio 1 con cantidad de huevos mayor a 30
df_final[df_final$huevos_sitio1 > 30, ] #aqui pedimos que nos tome la columna huevos_sitio1 y nos filtre las filas > 30 y que nos de todas las columnas

puntos_muestreo observador huevos_sitio1 huevos_sitio2 nidos_sitio1
1 P1              Juan       60            25            12          
5 P5              Martín     45            60             9          
9 P3              Ana y Juan 34            10             6          
  nidos_sitio2 Freq anios_muestreo temp_media
1  5           3    2022           25.5      
5 12           1    2022           25.5      
9  2           1    2023           30.7

In [94]:
# podemos obtener el mismo resultado si hacemos esto
df_final[df_final["huevos_sitio1"] > 30, ]

puntos_muestreo observador huevos_sitio1 huevos_sitio2 nidos_sitio1
1 P1              Juan       60            25            12          
5 P5              Martín     45            60             9          
9 P3              Ana y Juan 34            10             6          
  nidos_sitio2 Freq anios_muestreo temp_media
1  5           3    2022           25.5      
5 12           1    2022           25.5      
9  2           1    2023           30.7

In [95]:
# o si usamos la función subset()
subset(df_final, huevos_sitio1>30)

puntos_muestreo observador huevos_sitio1 huevos_sitio2 nidos_sitio1
1 P1              Juan       60            25            12          
5 P5              Martín     45            60             9          
9 P3              Ana y Juan 34            10             6          
  nidos_sitio2 Freq anios_muestreo temp_media
1  5           3    2022           25.5      
5 12           1    2022           25.5      
9  2           1    2023           30.7

In [96]:
# Filtar filas que contengan determinados nombres
df_final[df_final$observador %in% c("Ana", "Julia"), ]


puntos_muestreo observador huevos_sitio1 huevos_sitio2 nidos_sitio1
3 P3              Julia      20            10            4           
7 P1              Ana        23            25            4           
  nidos_sitio2 Freq anios_muestreo temp_media
3 2            2    2022           25.5      
7 5            2    2023           30.7

**Filtrar con míltiples condiciones**

In [97]:
# Filtar las observaciones que hizo Juan que tuvieron valores de frecuencia igual o menores a 2
df_final[df_final["observador"] == "Juan" & df_final["Freq"] <= 2, ]

puntos_muestreo observador huevos_sitio1 huevos_sitio2 nidos_sitio1
6 P6              Juan       15            45            3           
8 P2              Juan       10            17            2           
  nidos_sitio2 Freq anios_muestreo temp_media
6 9            2    2022           25.5      
8 3            2    2023           30.7

In [98]:
# lo mismo con subset
subset(df_final, observador== "Juan" & Freq <= 2)

puntos_muestreo observador huevos_sitio1 huevos_sitio2 nidos_sitio1
6 P6              Juan       15            45            3           
8 P2              Juan       10            17            2           
  nidos_sitio2 Freq anios_muestreo temp_media
6 9            2    2022           25.5      
8 3            2    2023           30.7

<a name='8.4'></a>
## 8.4) Listas

En R, una lista es una estructura de datos flexible y versátil que puede almacenar elementos de diferentes tipos (números, caracteres, vectores, matrices, data frames, incluso otras listas) en un único objeto. A diferencia de vectores, matrices o data frames, las listas no requieren que todos sus elementos sean del mismo tipo o longitud.

Podemos crear una lista con la función list(). Las listas pueden tener elementos con un nombre asignado o no. La diferencia es pequeña; en ambos casos, es util pensar en una lista como una gran caja llena de bolsas con todo tipo de cosas. Si estas bolsas están etiquetadas en lugar de numeradas, tienes una lista con elementos con nombre.

**Crear una lista sin nombres**

In [99]:
muestreo_sn <- list(muestreo_nidos, muestreo_huevos )
print(muestreo_sn)


[[1]]
             [,1] [,2] [,3] [,4] [,5] [,6]
nidos_sitio1   12    4    4    6    9    3
nidos_sitio2    5    3    2    2   12    9

[[2]]
     huevos_sitio1 huevos_sitio2
[1,]            60            25
[2,]            20            15
[3,]            20            10
[4,]            30            10
[5,]            45            60
[6,]            15            45



**Crear una lista con nombres**


In [100]:
mi_muestreo <- list(Nidos = muestreo_nidos, huevos = muestreo_huevos)
print(mi_muestreo)

$Nidos
             [,1] [,2] [,3] [,4] [,5] [,6]
nidos_sitio1   12    4    4    6    9    3
nidos_sitio2    5    3    2    2   12    9

$huevos
     huevos_sitio1 huevos_sitio2
[1,]            60            25
[2,]            20            15
[3,]            20            10
[4,]            30            10
[5,]            45            60
[6,]            15            45



In [101]:
#Puedo averiguar los nombres de los elementos de una lista con names()
names(mi_muestreo)

[1] "Nidos"  "huevos"

In [102]:
#Podemos saber la cantidad de elementos de la lista con length()
length(mi_muestreo)

[1] 2

**Acceder a los elementos de una lista**

En el caso de una lista con nombre, se puede acceder a los componentes usando el símbolo $, al igual que con los data frames.

Tanto para listas con nombre como sin nombre, se pueden usar otros dos métodos para acceder a los componentes de una lista:
* Usar [[ ]] proporciona el componente en sí, si por ejemplo el elemento de interés es una matriz devolvera una matriz.
* Usar [ ] proporciona una sublista con los componentes seleccionados, si por ejemplo el elemento es una matriz devolvera una lista con la matriz.

In [103]:
print(mi_muestreo$huevos)

     huevos_sitio1 huevos_sitio2
[1,]            60            25
[2,]            20            15
[3,]            20            10
[4,]            30            10
[5,]            45            60
[6,]            15            45


In [104]:
print(mi_muestreo[[2]])

     huevos_sitio1 huevos_sitio2
[1,]            60            25
[2,]            20            15
[3,]            20            10
[4,]            30            10
[5,]            45            60
[6,]            15            45


In [105]:
print(mi_muestreo[2]) #mirar el nombre de la lista huevos

$huevos
     huevos_sitio1 huevos_sitio2
[1,]            60            25
[2,]            20            15
[3,]            20            10
[4,]            30            10
[5,]            45            60
[6,]            15            45



Si por ejemplo queremos acceder a los datos de la columna 2 de la matriz de huevos de la lista mi_muestreo tengo que utilizar indices consecutivos

In [106]:
mi_muestreo[[2]][,2]

[1] 25 15 10 10 60 45

In [107]:
mi_muestreo[2][,2] #da error

#¿Por qué ocurre el error?
# mi_muestreo[2] devuelve una sub-lista (no la matriz directamente).
# Es equivalente a mi_muestreo[[2]] pero envuelto en una lista.
# Al intentar usar [, 2] sobre una lista (no una matriz), R no puede aplicar indexación bidimensional.

ERROR: Error in mi_muestreo[2][, 2]: número incorreto de dimensiones


**Cambiar o agregar componentes a una lista**


In [108]:
#Supongamos que tengo que actualizar mi matriz con datos de nidos
print(muestreo_nidos)

             [,1] [,2] [,3] [,4] [,5] [,6]
nidos_sitio1   12    4    4    6    9    3
nidos_sitio2    5    3    2    2   12    9


In [109]:
#Actualizo por ejemplo los valores del sitio 1
muestreo_nidos[1, ] <- c(14, 5,6,6,10,4)
print(muestreo_nidos)

             [,1] [,2] [,3] [,4] [,5] [,6]
nidos_sitio1   14    5    6    6   10    4
nidos_sitio2    5    3    2    2   12    9


In [110]:
# ahora tengo que agregar esta nueva matriz a mi lista mi_muestreo
#podría hacerlo así
mi_muestreo$Nidos <- muestreo_nidos
#o así
mi_muestreo[[2]] <- muestreo_nidos
print(mi_muestreo)

$Nidos
             [,1] [,2] [,3] [,4] [,5] [,6]
nidos_sitio1   14    5    6    6   10    4
nidos_sitio2    5    3    2    2   12    9

$huevos
             [,1] [,2] [,3] [,4] [,5] [,6]
nidos_sitio1   14    5    6    6   10    4
nidos_sitio2    5    3    2    2   12    9



**Agregar elementos nuevos a una lista**

In [111]:
# Podemos agregar nuevos elementos con nombre de la siguiente manera
temperatura_media_meses_muestreo <- c(35.2, 32.1, 27.4,25.7)

# Creando un nuevo elemento en la lista llamado temperatura
#Así,
mi_muestreo$temperatura <- temperatura_media_meses_muestreo
# o así:
mi_muestreo[["temperatura"]] <- temperatura_media_meses_muestreo

print(mi_muestreo)

$Nidos
             [,1] [,2] [,3] [,4] [,5] [,6]
nidos_sitio1   14    5    6    6   10    4
nidos_sitio2    5    3    2    2   12    9

$huevos
             [,1] [,2] [,3] [,4] [,5] [,6]
nidos_sitio1   14    5    6    6   10    4
nidos_sitio2    5    3    2    2   12    9

$temperatura
[1] 35.2 32.1 27.4 25.7



In [112]:
#Podemos agregar un elemento nuevo sin nombre simplemente agregando un elemento
# en un numero de indice superior al mayor de nuestra lista, como en los vectores

muestreo_sn[[3]] <- temperatura_media_meses_muestreo
print(muestreo_sn)



[[1]]
             [,1] [,2] [,3] [,4] [,5] [,6]
nidos_sitio1   12    4    4    6    9    3
nidos_sitio2    5    3    2    2   12    9

[[2]]
     huevos_sitio1 huevos_sitio2
[1,]            60            25
[2,]            20            15
[3,]            20            10
[4,]            30            10
[5,]            45            60
[6,]            15            45

[[3]]
[1] 35.2 32.1 27.4 25.7



**Eliminar un elemento**
Podemos eliminar un elemento con NULL

In [113]:
mi_muestreo[[3]] <- NULL
print(mi_muestreo)

$Nidos
             [,1] [,2] [,3] [,4] [,5] [,6]
nidos_sitio1   14    5    6    6   10    4
nidos_sitio2    5    3    2    2   12    9

$huevos
             [,1] [,2] [,3] [,4] [,5] [,6]
nidos_sitio1   14    5    6    6   10    4
nidos_sitio2    5    3    2    2   12    9



<a name='9'></a>
# 9) Referencias
* Zuur, Alain & Ieno, Elena & Meesters, Erik. (2009). A Beginner’s Guide to R. 10.1007/978-0-387-93837-0.
* Matloff, Norman (2011). The Art of R Programming: A Tour of Statistical Software Design. 978-1-59327-384-2.
* Crawley, Michael J. (2013). The R book. Chichester, West Sussex, United Kingdom :Wiley.